### ISSUE TITLE
「EX魔界ノ主」装備の属性耐性値にミスがある.

### ISSUE THREAD

**Issue by y-hashida** [iMasanari/mhw-simulator#59]
「EX魔界ノ主」装備の属性耐性値についてミスがあります.
シミュレーターの方では
* 雷: 1
* 氷: 4
となっていますが, 正しくは
シミュレーターの方では
* 雷: 4
* 氷: 1
のようです！

**Comment by iMasanari** [comment]
報告ありがとうございます。
修正しました。
